apps/moradores/urls.py
from django.urls import path
from django.conf import settings
from django.conf.urls.static import static
from . import views


from apps.moradores.views import (
    MoradorCreateView,
    MoradorListView,
    MoradorUpdateView,
    MoradorDeleteView,
    MoradorDetailView,
    
)



app_name = 'moradores'




urlpatterns = [
    path(
        'registrar/',
        views.MoradorCreateView.as_view(), 
        name='registrar'
    ),

    path(
        'listar/',
        views.MoradorListView.as_view(),
        name='listar'
    ),


    path(
        '<int:pk>',
        views.MoradorDetailView.as_view(),
        name = 'detalhe'
    ),

    path(
        '<int:pk>/atualizar',
        views.MoradorUpdateView.as_view(),
        name='atualizar'
    ),

    path(
        '<int:pk>/deletar',
        views.MoradorDeleteView.as_view(),
        name='deletar'
    )
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

controle_visitantes/urls.py
from django.contrib import admin
from django.urls import path, include

from django.contrib.auth import views as auth_views


from apps.dashboard.views import index

from apps.visitantes.views import (
    registrar_visitante,
    informacoes_visitante,
    finalizar_visita,
)




from django.conf.urls.static import static
from django.conf import settings
from apps.moradores import views




urlpatterns = [

    path(
        'admin/',
          admin.site.urls,
    ),

    path(
        'login/',
        auth_views.LoginView.as_view(
            template_name='login.html'

        ),
        name='login'
    ),
    path(
        'login/',
        auth_views.LogoutView.as_view(
            template_name='logout.html'

        ),
        name='logout'
    ),



    path(
        '',
        index,
        name = 'index',
    ),

    path(
        'registrar/',
        registrar_visitante,
        name = 'registrar_visitante',
    ),

    path(
        'visitantes/<int:id>/',
        informacoes_visitante,
        name = 'informacoes_visitante',
    ),
    path(
        'visitantes/<int:id>/finalizar-visita',
        finalizar_visita,
        name = 'finalizar_visita',
    ),

    path('moradores/', include(('apps.moradores.urls', 'moradores'), namespace='moradores'))
]

urlpatterns = urlpatterns + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

apps/moradores/models.py
from django.db import models

class Moradores(models.Model):
    nome_completo = models.CharField(
        max_length=100,
        blank=False

    )
    cpf = models.CharField(
        max_length=11,
        blank=False
    )
    data_nascimento = models.DateField()

    numero_casa = models.IntegerField(
        blank=False
    )

    placa_veiculo = models.CharField(
        max_length=7,
        blank=True
    )

    foto_morador = models.ImageField(
        upload_to='imagens/',
        blank=False
        

    )
    

    def get_cpf(self):
        if self.cpf:
            cpf = str(self.cpf)

            cpf_part_um = cpf[0:3]
            cpf_part_dois = cpf[3:6]
            cpf_part_tres = cpf[6:9]
            cpf_part_quatro = cpf[9:]

            cpf_formatado = f'{cpf_part_um}.{cpf_part_dois}.{cpf_part_tres}-{cpf_part_quatro}'

            return cpf_formatado

    def __str__(self):
        return self.nome_completo
    
    class Meta:
        verbose_name = 'Morador'
        verbose_name_plural = 'Moradores'
        db_table = 'morador'
       

apps/moradores/forms.py
from django import forms
from .models import Moradores


class MoradorForm(forms.ModelForm):
    class Meta:
        model = Moradores
        fields = [
            'nome_completo', 'cpf', 'data_nascimento', 'numero_casa', 'placa_veiculo', 'foto_morador'
        ]

        widgets = {
            'nome_completo': forms.TextInput(attrs={'placeholder': 'Nome Completo'}),
            'cpf': forms.TextInput(attrs={'placeholder': 'CPF'}),
            'data_nascimento': forms.DateInput(attrs={'type': 'date'}),
            'numero_casa': forms.TextInput(attrs={'placeholder': 'Numero da casa'}),
            'placa_veiculo': forms.TextInput(attrs={'placeholder': 'Placa do veiculo'}),
            
        }

        labels = {
            'nome_completo': 'Nome Completo',
            'cpf': 'CPF',
            'data_nascimento': 'Data de Nascimento',
            'numero_casa': 'Numero da casa',
            'placa_veiculo': 'Placa do veiculo',
            'foto_morador': 'Foto do morador',  
        }

        help_texts = {
            
        }
        error_messages = {
            'nome_completo': {
                'required': 'O nome completo do morador é obrigatório para o registro'
            },
        
            'cpf': {
                'required': 'O  CPF do morador é obrigatório para o registro'
                },
          
            'data_nascimento': {
                'required': 'A data de nascimento do morador é obrigatório para o registro',
                'invalid': 'Por favor, informe um formato válido para a data de nascimento (DD/MM/AAAA)'
            },
            'numero_casa': {
                'required': 'Por favor, informe o número da casa'
                },

            'foto_morador': {
                'required': 'Por favor, insira uma foto do morador'
                
            }

        }


    

apps/moradores/views.py
from .forms import MoradorForm
from .models import Moradores
from django.views.generic import CreateView, ListView, UpdateView, DeleteView, DetailView 
from django.contrib.auth.mixins import LoginRequiredMixin
from django.urls import reverse_lazy






class MoradorDetailView(LoginRequiredMixin, DetailView):
    model = Moradores
    template_name = 'info_morador.html'
    context_object_name = 'morador'
    
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        return context



class MoradorCreateView(LoginRequiredMixin, CreateView):
    model = Moradores
    form_class = MoradorForm
    template_name = 'registrar_morador.html'
    success_url = reverse_lazy('index')


class MoradorUpdateView(LoginRequiredMixin, UpdateView):
    model = Moradores
    form_class = MoradorForm
    template_name = 'atualizar_morador.html'
    context_object_name = 'moradores'
    success_url = reverse_lazy('view_morador')
    

    def form_invalid(self, form):
        return self.render_to_response(self.get_context_data(form=form))


class MoradorListView(LoginRequiredMixin, ListView):
    model = Moradores
    template_name = 'view_morador.html'
    context_object_name = 'moradores'
    paginate_by = 5

    def get_queryset(self):
        # Ordene the QuerySet pelo a campo específico, for example, 'criado'
        return Moradores.objects.all().order_by('-numero_casa')


class MoradorDeleteView(LoginRequiredMixin, DeleteView):
    model = Moradores
    template_name = 'deletar_morador.html'
    success_url = reverse_lazy('index')









    





   

apps/moradores/templates/atualizar_morador.html
{% extends "base.html" %}

{% load widget_tweaks %}

{% load static %}

{% block conteudo %}

{% block title %}Informações Morador{% endblock %}




<div class="container">
    <div class="d-sm-flex align-items-center justify-content-between mb-4">
        <h1 class="h3 mb-0 text-gray-800">{{ nome_pagina }}</h1>
    </div>

    <div class="card shadow mb-4">
        <div class="card-body">
            <h4 class="mb-3 text-primary">
                Atualizar Informações Prediais
            </h4>

            
        <div class="card">
            <div class="card-body">
                <form method="post" action="{% url "moradores:atualizar" pk=moradores.pk %}">
                    {% csrf_token %}
                    {{ form.numero_casa }}
                    {{ form.placa_veiculo }}
                    <br>
                    <button type="submit" class="btn btn-primary" value="Update">Salvar</button>
                </form>
            </div>
        </div>
        
    
            
    </div> 

{% endblock %}

apps/moradores/templates/deletar_morador.html
{% extends "base.html" %}

{% load widget_tweaks %}

{% load static %}

{% block conteudo %}

{% block title %}Informações Morador{% endblock %}




<div class="container">
    <div class="d-sm-flex align-items-center justify-content-between mb-4">
        <h1 class="h3 mb-0 text-gray-800">{{ nome_pagina }}</h1>
    </div>

    <div class="card shadow mb-4">
        <div class="card-body">
            <h4 class="mb-3 text-primary">
                Deletar cadastro de morador
            </h4>
        </div>
    </div>



<div class="card">
    <div class="card-body">
        <h4>Tem certeza que deseja remover {{morador.nome_completo}} do sistema?</h4>
        <hr>
        <form method="POST" action="{% url 'moradores:deletar' pk=morador.pk %}">
            {% csrf_token %}
            <p class="card-text">
                {{ morador.nome_completo }}
                            {{ morador.get_cpf }}
                            {{ morador.data_nascimento }}
                            {{ morador.numero_casa }}
                            {{morador.placa_veiculo}}
                                

            <button type="submit" class="btn btn-danger">Remover</button>
            <a href="{% url 'index' %}" class="btn btn-secondary">Voltar</a>
        </form>
    </div>
</div>

{% endblock %}

apps/moradores/templates/info_morador.html
{% extends "base.html" %}

{% load widget_tweaks %}

{% load static %}

{% block conteudo %}

{% block title %}Informações Morador{% endblock %}




<div class="container">
    <div class="d-sm-flex align-items-center justify-content-between mb-4">
        <h1 class="h3 mb-0 text-gray-800">{{ nome_pagina }}</h1>
    </div>

    <div class="card shadow mb-4">
        <div class="card-body">
            <h4 class="mb-3 text-primary">
                Informações Pessoais
            </h4>

            

        <div class="container">
            <div class="card-body mt-5">
                <div class="d-flex justify-content-end align-items-start top-right">
                    <div class="card" style="width: 10rem;">
                        {% if morador.foto_morador %}
                        <img class="img-thumbnail" src="{{ morador.foto_morador.url }}" alt="Card image cap" width="200" height="200">
                        {% endif %}
                    </div>
                </div>
            </div>
        </div>

        <div>ㅤ</div>
        <div>ㅤ</div>
        <div>ㅤ</div>
        
        
    
        <form>
            
                <div class="form-row mt-5">
                    <div class="form-group col-md-6">
                        <label>Nome completo</label>
                        <input type="text" class="form-control" value="{{ morador.nome_completo }}" disabled>
                    </div>

                    <div class="form-group col-md-6">
                        <label>CPF</label>
                        <input type="text" class="form-control" value="{{ morador.get_cpf }}" disabled>
                    </div>
                </div>

                <div class="form-row">
                    <div class="form-group col-md-6">
                        <label>Data de nascimento</label>
                        <input type="text" class="form-control" value="{{ morador.data_nascimento }}" disabled>
                    </div>

                    <div class="form-group col-md-6">
                        <label>Placa do veículo</label>
                        <input type="text" class="form-control" value="{{ morador.placa_veiculo }}" disabled>
                    </div>

                    <div class="form-group col-md-6">
                        <label>Número da casa</label>
                        <input type="text" class="form-control" value="{{ morador.numero_casa }}" disabled>
                    </div>
                </div>
        </form>
        <div class="card-footer">
            <a href="{% url 'moradores:deletar' pk=morador.pk %}" class="btn btn-danger">Remover</a>
            <a href="{% url 'moradores:atualizar' pk=morador.pk %}" class="btn btn-primary">Editar</a>
            <a href="{% url 'moradores:listar' %}" class="btn btn-secondary">Voltar</a>
      </div> 
    </div> 

{% endblock %}

apps/moradores/templates/registrar_morador.html
{% extends 'base.html' %}
 
{% load widget_tweaks %}
 
{% block conteudo %}

{% block title %}Registro Morador{% endblock %}

<div class="container">
                        <div class="d-sm-flex align-items-center justify-content-between mb-4">
                            <h1 class="h3 mb-0 text-gray-800">{{ nome_pagina }}</h1>
                        </div>
 
                        <div class="card shadow mb-4">
                            <div class="card-body">
                                <h4 class="mb-3 text-primary">
                                    Formulário para registro de novo Morador
                                </h4>

                                <p class="mb-5 ml-1">
                                    <small>
                                        O asterístico (*) indica que o campo é OBRIGATÓRIO.
                                    </small>
                                </p>

                                {% if form.errors %}
                                    {% for field in form %}
                                        {% if field.errors %}
                                            {% for erro in field.errors %}
                                                <div class="alert alert-warning" role="alert">
                                                    {{ erro }}
                                                </div>
                                            {% endfor %}
                                        {% endif %}
                                    {% endfor %}
                                {% endif %}
 
                                <form method=POST enctype="multipart/form-data">
                                    <div class="form-row">
                                        {% csrf_token %}
 
                                        {% for field in form %}
                                            <div class="form-group col-md-12">
                                                <label>{{ field.label }} {% if field.field.required %} * {% endif %}</label>
                                                {% render_field field placeholder=field.label class="form-control" %}
                                            </div>
                                        {% endfor %}
 
                                    </div>
                                    <div class='text-rigth'> 
                                        <a href="{% url 'moradores:listar' %}" class="btn btn-secondary text-white" type="button">
                                        <span class="text">Cancelar</span>
                                    </a>
                                    
                                        <button class="btn btn-primary" type="submit">
                                            <span class="text">Registrar Morador</span>

                                        </button>
                                    </div>
                                </form>
 
                            </div>
                        </div>
                    </div>
{% endblock conteudo %}

apps/moradores/templates/view_morador.html
{% extends "base.html" %}
{% load widget_tweaks %}
{% load static %}

{% block conteudo %}

{% block title %}Banco Moradores{% endblock %}

<div class="container">
    <div class="d-sm-flex align-items-center justify-content-between mb-4">
    <h1 class="h3 mb-0 text-gray-800">{{ nome_pagina }}</h1>
    </div>

                        <div class="card shadow mb-4">
                            <div class="card-body">
                                <h4 class="mb-3 text-primary">
                                    Database moradores
                                </h4>

                                <p class="mb-5 ml-1">
                                    <small>
                                        Presença de todos os moradores ativos no prédio
                                    </small>
                                </p>
            
            <table class="table">
                <thead>
                    
                    <tr>
                        <th>Nome</th>
                        <th>CPF</th>
                        <th>Data de nascimento</th>
                        <th>Número da casa</th>
                        <th>Placa do veículo</th>
                        <th>Mais informações</th>
                        
                    
                    </tr>
                </thead>
                <tbody id="tabela-corpo">
                    {% for morador in moradores %}
                        <tr>
                            <td>{{ morador.nome_completo }}</td>
                            <td>{{ morador.get_cpf }}</td>
                            <td>{{ morador.data_nascimento }}</td>
                            <td>{{ morador.numero_casa }}</td>
                            <td>{% if morador.placa_veiculo %}
                                {{ morador.placa_veiculo }}
                                {% else %}
                                    N/A
                                {% endif %}</td>
                            <td><a href="{% url 'moradores:detalhe' pk=morador.pk %}">Informações</a></td>
                            
                            
                        </tr>
                    {% endfor %}
                </tbody>
            </table>
            <script src={% static 'js/ordernarTabela.js' %}></script>
        </div>
    </div>



{% endblock %}