apps/moradores/urls.py
from django.urls import path
from django.conf import settings
from django.conf.urls.static import static
from . import views


from apps.moradores.views import (
    MoradorCreateView,
    MoradorListView,
    MoradorUpdateView,
    MoradorDeleteView,
    MoradorDetailView,
    
)



app_name = 'moradores'




urlpatterns = [
    path(
        'registrar/',
        views.MoradorCreateView.as_view(), 
        name='registrar'
    ),

    path(
        'listar/',
        views.MoradorListView.as_view(),
        name='listar'
    ),


    path(
        '<int:pk>',
        views.MoradorDetailView.as_view(),
        name = 'detalhe'
    ),

    path(
        '<int:pk>/atualizar',
        views.MoradorUpdateView.as_view(),
        name='atualizar'
    ),

    path(
        '<int:pk>/deletar',
        views.MoradorDeleteView.as_view(),
        name='deletar'
    )
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

controle_visitantes/urls.py
from django.contrib import admin
from django.urls import path, include

from django.contrib.auth import views as auth_views


from apps.dashboard.views import index

from apps.visitantes.views import (
    registrar_visitante,
    informacoes_visitante,
    finalizar_visita,
)




from django.conf.urls.static import static
from django.conf import settings
from apps.moradores import views




urlpatterns = [

    path(
        'admin/',
          admin.site.urls,
    ),

    path(
        'login/',
        auth_views.LoginView.as_view(
            template_name='login.html'

        ),
        name='login'
    ),
    path(
        'login/',
        auth_views.LogoutView.as_view(
            template_name='logout.html'

        ),
        name='logout'
    ),



    path(
        '',
        index,
        name = 'index',
    ),

    path(
        'registrar/',
        registrar_visitante,
        name = 'registrar_visitante',
    ),

    path(
        'visitantes/<int:id>/',
        informacoes_visitante,
        name = 'informacoes_visitante',
    ),
    path(
        'visitantes/<int:id>/finalizar-visita',
        finalizar_visita,
        name = 'finalizar_visita',
    ),

    path('moradores/', include(('apps.moradores.urls', 'moradores'), namespace='moradores'))
]

urlpatterns = urlpatterns + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

apps/visitantes/models.py
from django.db import models

class Visitantes(models.Model):

    STATUS_VISITANTE = [
        ('AGUARDANDO', 'Aguardando Autorização'),
        ('EM_VISITA', 'Em visita'),
        ('FINALIZADO', 'Visita Finalizada'),
    ]

    status = models.CharField(
        verbose_name='Status',
        max_length = 10,
        choices = STATUS_VISITANTE,
        default = 'AGUARDANDO',
    )

    nome_completo = models.CharField(
        verbose_name = 'Nome Completo',
        max_length = 100
    )

    cpf = models.CharField(
        verbose_name = 'CPF do Visitante',
        max_length = 11
    )

    data_nascimento = models.DateField(
        verbose_name = 'Data de Nascimento do Visitante',
        auto_now = False,
        auto_now_add = False
    )

    numero_casa = models.PositiveSmallIntegerField(
        verbose_name = 'Número da casa a ser visitada',
    )

    placa_veiculo = models.CharField(
        verbose_name = 'Placa do Veículo',
        max_length = 7,
        blank= True,
        null = True
    )

    horario_chegada = models.DateTimeField(
        verbose_name = 'Horário de chegada na portaria',
        auto_now_add = True

    )

    horario_saida = models.DateTimeField(
        verbose_name = 'Horário de saida do condomínio',
        auto_now_add = False,
        blank=True,
        null=True,

    )

    horario_autorizacao = models.DateTimeField(
        verbose_name = 'Horário de Autorização da Entrada',
        auto_now = False,
        blank = True,
        null = True,
    )

    morador_responsavel = models.CharField(
        verbose_name = 'Morador que autorizou a Entrada do visitante',
        max_length = 100,
        blank = True
    )

    registrado_por = models.ForeignKey(
        'porteiros.Porteiro',
        verbose_name = 'Porteiro responsável pelo registro',
        on_delete = models.PROTECT
    )

    def get_horario_saida(self):
        if self.horario_saida:
            return self.horario_saida
        
        return 'Horário de saída não registrado'
    
    def get_horario_autorizacao(self):
        if self.horario_autorizacao:
            return self.horario_autorizacao
        
        return 'Visitante aguardando autorização'
    
    def get_morador_responsavel(self):
        if self.morador_responsavel:
            return self.morador_responsavel
        
        return 'Visitante aguardando autorização'
    
    def get_placa_veiculo(self):
        if self.placa_veiculo:
            return self.placa_veiculo
    
        return 'Veículo não registrado'
    
    def get_cpf(self):
        if self.cpf:
            cpf = str(self.cpf)

            cpf_part_um = cpf[0:3]
            cpf_part_dois = cpf[3:6]
            cpf_part_tres = cpf[6:9]
            cpf_part_quatro = cpf[9:]

            cpf_formatado = f'{cpf_part_um}.{cpf_part_dois}.{cpf_part_tres}-{cpf_part_quatro}'

            return cpf_formatado
    


    class Meta:
        verbose_name = 'Visitante'
        verbose_name_plural = 'Visitantes'
        db_table = 'visitante'

    def __str__(self):
        return self.nome_completo

templates/base.html
<!DOCTYPE html>

{% load static %}

<html lang="pt-BR">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">
    
    <title>SystemX | {% block title %}Dashboard{% endblock %}</title>
    
    <link href="https://fonts.googleapis.com/css?family=Nunito:200,200i,300,300i,400,400i,600,600i,700,700i,800,800i,900,900i" rel="stylesheet">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.11.3/font/bootstrap-icons.min.css">
    <link href="{% static 'css/sb-admin-2.min.css' %}" rel="stylesheet">    
    <link href="{% static 'vendor/fontawesome-free/css/all.min.css' %}" rel="stylesheet" type="text/css">
    <link rel="icon" href="{% static 'img/favicon.ico' %}" type="image/x-icon">

    <style>
        .top-right {
            position: absolute;
            top: 20px;
            right: 20px;


        }
        
        
    </style>

</head>

<body id="page-top">
    <div id="wrapper">
        <ul class="navbar-nav bg-gradient-primary sidebar sidebar-dark accordion" id="accordionSidebar">
            <a class="sidebar-brand d-flex align-items-center justify-content-center" href="#">
                <div class="sidebar-brand-icon rotate-n-15">
                    <i class="fas fa-user-shield"></i>
                </div>
                
                <div class="sidebar-brand-text">SystemX Gerenciamento</div>
            </a>
            
            <hr class="sidebar-divider my-0">
            
            <li class="nav-item">
                <a class="nav-link" href="{% url 'index' %}">
                    <i class="bi bi-card-list"></i>
                    <span>Dashboard visitas</span>
                </a>
            </li>
            
            <hr class="sidebar-divider">

            
            <li class="nav-item">
                <a class="nav-link" href="{% url 'moradores:registrar' %}">
                    <i class="fas fa-home"></i>
                    <span>Registrar Morador</span>
                </a>
            </li>

            <hr class="sidebar-divider">

            <li class="nav-item">
                <a class="nav-link" href="{% url 'moradores:listar' %}">
                    <i class="bi bi-database"></i>
                    <span>Database Moradores</span>
                </a>
            </li>

                <hr class="sidebar-divider">
    </ul>  

        

            
    

    

        
        

        <div id="content-wrapper" class="d-flex flex-column">
            <div id="content">
                <nav class="navbar navbar-expand navbar-light bg-white topbar mb-4 static-top shadow">
                    <button id="sidebarToggleTop" class="btn btn-link d-md-none rounded-circle mr-3">
                        <i class="fa fa-bars"></i>
                    </button>
                    
                    <ul class="navbar-nav ml-auto">
                        <li class="nav-item dropdown no-arrow">
                            <a class="nav-link dropdown-toggle" href="#" id="userDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                <span class="mr-2 d-none d-lg-inline text-gray-800 small">{{ request.user.email }}</span>
                            </a>
                            
                            <div class="dropdown-menu dropdown-menu-right shadow animated--grow-in" aria-labelledby="userDropdown">
                                <a class="dropdown-item" href="#" data-toggle="modal" data-target="#logoutModal">
                                    <i class="fas fa-sign-out-alt fa-sm fa-fw mr-2 text-gray-400"></i>
                                    Sair
                                </a>
                            </div>
                        </li>
                    </ul>
                </nav>

                {% block conteudo %} {% endblock conteudo %}

                <footer class="sticky-footer bg-white">
                    <div class="container my-auto">
                        <div class="copyright text-center my-auto">
                            <span>Controle de visitantes &copy; luc</span>
                        </div>
                    </div>
                </footer>
            </div>
        </div>

        <div class="modal fade" id="logoutModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
            <div class="modal-dialog" role="document">
                <div class="modal-content">
                    <div class="modal-header">
                        <h5 class="modal-title" id="exampleModalLabel">Você realmente deseja sair?</h5>
                        
                        <button class="close" type="button" data-dismiss="modal" aria-label="Close">
                            <span aria-hidden="true">×</span>
                        </button>
                    </div>
                    
                    <div class="modal-body">Selecione "sair" se realmente deseja sair</div>
                    <div class="modal-footer">
                        <button class="btn btn-secondary" type="button" data-dismiss="modal">Cancelar</button>
                        <a class="btn btn-primary" href="{% url 'logout' %}">Sair</a>
                    </div>
                </div>
            </div>
        </div>
    </div>
                    
                </div>
            </div>
        </div>
    </div>

    <script src="{% static 'vendor/jquery/jquery.min.js' %}"></script>
    <script src="{% static 'vendor/bootstrap/js/bootstrap.bundle.min.js' %}"></script>
    <script src="{% static 'js/sb-admin-2.min.js' %}"></script>
</body>
</html>

templates/index.html
{% extends 'base.html' %}


{% block conteudo %}

{% block title %}Dashboard{% endblock %}

<div class="container-fluid">
    <div class="d-sm-flex align-items-center justify-content-between mb-4">
        <h1 class="h3 mb-0 text-gray-800">Seja bem vindo, {{ porteiro_nome }}.</h1>

        <a href="{% url 'registrar_visitante' %}" class="btn btn-primary btn-icon-split btn-sm">

            <span class="text">Registrar Visitante</span>

            <span class="icn text-white-50">
                <i class="fas fa-user-plus"></i>
            </span>
        </a>
    </div>

    {% if messages %}
        {% for message in messages %}
            <div class="alert alert-dismissible alert-{{ message.tags }}" role="alert">
                {{ message }}
                <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
        {% endfor %}
    {% endif %}

    <div class="row">
        <div class="col-xl-3 col-md-6 mb-4">
            <div class="card border-left-warning shadow h-100 py-2">
                <div class="card-body">
                    <div class="row no-gutters align-items-center">
                        <div class="col mr-2">
                            <div class="text-xs font-weight-bold text-warning text-uppercase mb-1">Visitantes aguardando autorização</div>
                            <div class="h5 mb-0 font-weight-bold text-gray-800">{{ visitantes_aguardando }}</div>
                        </div>
                        
                        <div class="col-auto">
                            <i class="fas fa-user-lock fa-2x text-gray-300"></i>
                        </div>
                    </div>
                </div>
            </div>
        </div>

        <div class="col-xl-3 col-md-6 mb-4">
            <div class="card border-left-primary shadow h-100 py-2">
                <div class="card-body">
                    <div class="row no-gutters align-items-center">
                        <div class="col mr-2">
                            <div class="text-xs font-weight-bold text-primary text-uppercase mb-1">Visitantes no condomínio</div>
                            <div class="h5 mb-0 font-weight-bold text-gray-800">{{ visitantes_em_visita }}</div>
                        </div>
                        
                        <div class="col-auto">
                            <i class="fas fa-user-clock fa-2x text-gray-300"></i>
                        </div>
                    </div>
                </div>
            </div>
        </div>

        <div class="col-xl-3 col-md-6 mb-4">
            <div class="card border-left-success shadow h-100 py-2">
                <div class="card-body">
                    <div class="row no-gutters align-items-center">
                        <div class="col mr-2">
                            <div class="text-xs font-weight-bold text-success text-uppercase mb-1">Visitas finalizadas</div>
                            <div class="h5 mb-0 font-weight-bold text-gray-800">{{ visitantes_finalizado }}</div>
                        </div>
                        <div class="col-auto">
                            <i class="fas fa-user-check fa-2x text-gray-300"></i>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        
        <div class="col-xl-3 col-md-6 mb-4">
            <div class="card border-left-info shadow h-100 py-2">
                <div class="card-body">
                    <div class="row no-gutters align-items-center">
                        <div class="col mr-2">
                            <div class="text-xs font-weight-bold text-info text-uppercase mb-1">Visitantes registrados no mês atual</div>
                            <div class="h5 mb-0 font-weight-bold text-gray-800">{{ visitantes_mes }}</div>
                        </div>
                        <div class="col-auto">
                            <i class="fas fa-users fa-2x text-gray-300"></i>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    
    <div class="card shadow mb-4">
        <div class="card-header py-3 d-sm-flex align-items-center justify-content-between mb-4">
            <h6 class="m-0 font-weight-bold text-primary">Visitantes recentes</h6>
        </div>

        <div class="card-body">
            <div class="table-responsive">
                <table class="table table-bordered">
                    <thead>
                        <th>Nome completo</th>
                        <th>CPF</th>
                        <th>Horário de chegada</th>
                        <th>Status</th>
                        <th>Horário da autorização</th>
                        <th>Autorizado por</th>
                        <th>Mais informações</th>
                    </thead>

                    <tbody>
                        {% for visitante in todos_visitantes %}
                        <tr>
                            <td>{{ visitante.nome_completo }}</td>
                            <td>{{ visitante.get_cpf }}</td>
                            <td>{{ visitante.horario_chegada }}</td>
                            <td>{{ visitante.get_status_display }}</td>
                            <td>{{ visitante.get_horario_autorizacao }}</td>
                            <td>{{ visitante.get_morador_responsavel }}</td>
                            <td>
                                <a href="{% url 'informacoes_visitante' id=visitante.id %}">
                                    Ver informações
                                </a>
                            </td>
                        </tr>
                        {% endfor %}
                    </tbody>
                </table>
            </div>
        </div>
    </div>
</div>
{% endblock conteudo %}

templates/login.html
<!DOCTYPE html>

{% load static %}
{% load widget_tweaks %}



<html lang="pt-br">
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
        
        <title>SystemX | Autenticação</title>
        
        <link href="https://fonts.googleapis.com/css?family=Nunito:200,200i,300,300i,400,400i,600,600i,700,700i,800,800i,900,900i" rel="stylesheet">
        
        <link href="{% static 'css/sb-admin-2.min.css' %}" rel="stylesheet">    
        <link href="{% static 'vendor/fontawesome-free/css/all.min.css' %}" rel="stylesheet" type="text/css">
    </head>

    <body class="bg-gradient-primary">
        <div class="container">
            <div class="row justify-content-center">
                <div class="col-xl-10 col-lg-12 col-md-9">
                    <div class="card o-hidden border-0 shadow-lg my-5">
                        <div class="card-body p-0">
                            <div class="row">
                                <div class="col-lg-6 d-none d-lg-block bg-login-image"></div>
    
                                <div class="col-lg-6">
                                    <div class="p-5">
                                        <div class="text-left mb-5">
                                            <h1 class="h4 text-gray-900 mb-1">Seja bem-vindo!</h1>
    
                                            <p>Faça login para continuar</p>
                                        </div>

                                        {% if form.errors %}
                                            <div class="alert alert-warning" role="alert"></div>
                                        {% endif %}
    
                                        <form method="post" class="user">
                                            <div class="form-row">
                                                {% csrf_token %}

                                                {% for field in form  %}
                                                <div class="form-group col-md-12">
                                                    {% render_field field placeholder=fild.label class='form-control form-control user' %}
                                                </div>
                                                {% endfor %}
                                            </div>
    
                                            <button class="btn btn-primary btn-user btn-block" type="submit">
                                                <span class="text">Acessar dashboard</span>
                                            </button>
                                        </form>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                    
                </div>
                
            </div>
        </div>
        
        <script src="{% static 'vendor/jquery/jquery.min.js' %}"></script>
        <script src="{% static 'vendor/bootstrap/js/bootstrap.bundle.min.js' %}"></script>
        <script src="{% static 'js/sb-admin-2.min.js' %}"></script>
    </body>
</html>

templates/logout.html
<!DOCTYPE html>

{% load static %}
{% load widget_tweaks %}



<html lang="pt-br">
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
        
        <title>SystemX | Logout</title>
        
        <link href="https://fonts.googleapis.com/css?family=Nunito:200,200i,300,300i,400,400i,600,600i,700,700i,800,800i,900,900i" rel="stylesheet">
        
        <link href="{% static 'css/sb-admin-2.min.css' %}" rel="stylesheet">    
        <link href="{% static 'vendor/fontawesome-free/css/all.min.css' %}" rel="stylesheet" type="text/css">
    </head>

    <body class="bg-gradient-primary">
        <div class="container">
            <div class="row justify-content-center">
                <div class="col-xl-10 col-lg-12 col-md-9">
                    <div class="card o-hidden border-0 shadow-lg my-5">
                        <div class="card-body p-0">
                            <div class="row">
                                <div class="col-lg-6 d-none d-lg-block bg-login-image"></div>

                                <div class="col-lg-6">
                                    <div class="p-5">
                                        <div class="text-left mb-5">
                                            <h1 class="h4 text-gray-900 mb-1">Até a próxima!</h1>

                                            <p>Você escolheu sair da dashboard, mas se preferir fazer login novamente, basta clicar no botão abaixo para voltar à página de login</p>
                                        </div>

                                        <a href="{% url 'login' %}" class="btn btn-primary btn-user btn-block">
                                            <span class="text">Voltar para login</span>
                                        </a>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        
        <script src="{% static 'vendor/jquery/jquery.min.js' %}"></script>
        <script src="{% static 'vendor/bootstrap/js/bootstrap.bundle.min.js' %}"></script>
        <script src="{% static 'js/sb-admin-2.min.js' %}"></script>
    </body>
</html>