controle_visitantes/urls.py
from django.contrib import admin
from django.urls import path, include

from django.contrib.auth import views as auth_views


from apps.dashboard.views import index

from apps.visitantes.views import (
    registrar_visitante,
    informacoes_visitante,
    finalizar_visita,
)




from django.conf.urls.static import static
from django.conf import settings
from apps.moradores import views




urlpatterns = [

    path(
        'admin/',
          admin.site.urls,
    ),

    path(
        'login/',
        auth_views.LoginView.as_view(
            template_name='login.html'

        ),
        name='login'
    ),
    path(
        'login/',
        auth_views.LogoutView.as_view(
            template_name='logout.html'

        ),
        name='logout'
    ),



    path(
        '',
        index,
        name = 'index',
    ),

    path(
        'registrar/',
        registrar_visitante,
        name = 'registrar_visitante',
    ),

    path(
        'visitantes/<int:id>/',
        informacoes_visitante,
        name = 'informacoes_visitante',
    ),
    path(
        'visitantes/<int:id>/finalizar-visita',
        finalizar_visita,
        name = 'finalizar_visita',
    ),

    path('moradores/', include(('apps.moradores.urls', 'moradores'), namespace='moradores'))
]

urlpatterns = urlpatterns + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

apps/visitantes/models.py
from django.db import models

class Visitantes(models.Model):

    STATUS_VISITANTE = [
        ('AGUARDANDO', 'Aguardando Autorização'),
        ('EM_VISITA', 'Em visita'),
        ('FINALIZADO', 'Visita Finalizada'),
    ]

    status = models.CharField(
        verbose_name='Status',
        max_length = 10,
        choices = STATUS_VISITANTE,
        default = 'AGUARDANDO',
    )

    nome_completo = models.CharField(
        verbose_name = 'Nome Completo',
        max_length = 100
    )

    cpf = models.CharField(
        verbose_name = 'CPF do Visitante',
        max_length = 11
    )

    data_nascimento = models.DateField(
        verbose_name = 'Data de Nascimento do Visitante',
        auto_now = False,
        auto_now_add = False
    )

    numero_casa = models.PositiveSmallIntegerField(
        verbose_name = 'Número da casa a ser visitada',
    )

    placa_veiculo = models.CharField(
        verbose_name = 'Placa do Veículo',
        max_length = 7,
        blank= True,
        null = True
    )

    horario_chegada = models.DateTimeField(
        verbose_name = 'Horário de chegada na portaria',
        auto_now_add = True

    )

    horario_saida = models.DateTimeField(
        verbose_name = 'Horário de saida do condomínio',
        auto_now_add = False,
        blank=True,
        null=True,

    )

    horario_autorizacao = models.DateTimeField(
        verbose_name = 'Horário de Autorização da Entrada',
        auto_now = False,
        blank = True,
        null = True,
    )

    morador_responsavel = models.CharField(
        verbose_name = 'Morador que autorizou a Entrada do visitante',
        max_length = 100,
        blank = True
    )

    registrado_por = models.ForeignKey(
        'porteiros.Porteiro',
        verbose_name = 'Porteiro responsável pelo registro',
        on_delete = models.PROTECT
    )

    def get_horario_saida(self):
        if self.horario_saida:
            return self.horario_saida
        
        return 'Horário de saída não registrado'
    
    def get_horario_autorizacao(self):
        if self.horario_autorizacao:
            return self.horario_autorizacao
        
        return 'Visitante aguardando autorização'
    
    def get_morador_responsavel(self):
        if self.morador_responsavel:
            return self.morador_responsavel
        
        return 'Visitante aguardando autorização'
    
    def get_placa_veiculo(self):
        if self.placa_veiculo:
            return self.placa_veiculo
    
        return 'Veículo não registrado'
    
    def get_cpf(self):
        if self.cpf:
            cpf = str(self.cpf)

            cpf_part_um = cpf[0:3]
            cpf_part_dois = cpf[3:6]
            cpf_part_tres = cpf[6:9]
            cpf_part_quatro = cpf[9:]

            cpf_formatado = f'{cpf_part_um}.{cpf_part_dois}.{cpf_part_tres}-{cpf_part_quatro}'

            return cpf_formatado
    


    class Meta:
        verbose_name = 'Visitante'
        verbose_name_plural = 'Visitantes'
        db_table = 'visitante'

    def __str__(self):
        return self.nome_completo

apps/visitantes/forms.py
from django import forms
from .models import Visitantes

class VisitanteForm(forms.ModelForm):
    class Meta:
        model = Visitantes
        fields = [
            'nome_completo', 'cpf', 'data_nascimento', 'numero_casa', 'placa_veiculo'
        ]

        error_messages = {
            'nome_completo': {
                'required': 'O nome completo do visitante é obrigatório para o registro'
            },
        
            'cpf': {
                'required': 'O  CPF do visitante é obrigatório para o registro'
                },
          
            'data_nascimento': {
                'required': 'A data de nascimento do visitante é obrigatório para o registro',
                'invalid': 'Por favor, informe um formato válido para a data de nascimento (DD/MM/AAAA)'
            },
            'numero_casa': {
                'required': 'Por favor, informe o número da casa a ser visitada'
                },

        }

class AutorizaVisitanteForm(forms.ModelForm):

    morador_responsavel = forms.CharField(required=True)

    class Meta:
        model = Visitantes
        fields = [
            'morador_responsavel'
        ]

        error_messages = {
            'morador_responsavel': {
                'required': 'Por favor, informe o nome do morador responsável por autorizar a entrada do visitante!'
            }
        }

apps/visitantes/views.py
from django.contrib import messages
from django.shortcuts import (
    render, redirect, get_object_or_404
)
from django.contrib.auth.decorators import login_required
from django.http import HttpResponseNotAllowed


from .models import Visitantes
from .forms import VisitanteForm, AutorizaVisitanteForm

from datetime import datetime


@login_required
def registrar_visitante(request):

    form = VisitanteForm()

    if request.method == "POST":
        form = VisitanteForm(request.POST)

        if form.is_valid():
            visitante = form.save(commit=False)
            visitante.registrado_por = request.user.porteiro

            visitante.save()

            messages.success(
                request,
                "Visitante registrado com sucesso"
            )

            return redirect("index")

    context = {
        "nome_pagina": "Registrar visitante",
        "form": form,
    }

    return render(request, "registrar_visitante.html", context)


@login_required
def informacoes_visitante(request, id):

    form = AutorizaVisitanteForm()
    visitante = get_object_or_404(Visitantes, id=id)

    if request.method == "POST":
        form = AutorizaVisitanteForm(request.POST, instance=visitante)

        if form.is_valid():
            visitante = form.save(commit=False)

            visitante.status = "EM_VISITA"
            visitante.horario_autorizacao = datetime.now()

            visitante.save()

            messages.success(
                request,
                "Entrada de visitante autorizada com sucesso"
            )

            return redirect("index")

    context = {
        "nome_pagina": "Informações de visitante",
        "visitante": visitante,
        "form": form,
    }

    return render(request, "informacoes_visitante.html", context)


@login_required
def finalizar_visita(request, id):

    if request.method == "POST":
        visitante = get_object_or_404(Visitantes, id=id)

        visitante.status = "FINALIZADO"
        visitante.horario_saida = datetime.now()

        visitante.save()

        messages.success(
            request,
            "Visita finalizada com sucesso"
        )

        return redirect("index")

    else:
        return HttpResponseNotAllowed(
            ["POST"],
            "Método não permitido"
        )

apps/visitantes/templates/informacoes_visitante.html
{% extends "base.html" %}

{% load widget_tweaks %}

{% block conteudo %}

{% block title %}Informações Visitante{% endblock %}


<div class="container">
    <div class="d-sm-flex align-items-center justify-content-between mb-4">
        <h1 class="h3 mb-0 text-gray-800">{{ nome_pagina }}</h1>
        
        <div class="">
            {% if visitante.status == "AGUARDANDO" %}
                <a href="#" class="btn btn-success btn-icon-split btn-sm" data-toggle="modal" data-target="#modal1">
                    <span class="text">Autorizar entrada</span>
                    
                    <span class="icon text-white-50">
                        <i class="fas fa-user-check"></i>
                    </span>
                </a>
            {% endif %}

            {% if visitante.status == "EM_VISITA" %}
                <a href="#" class="btn btn-warning btn-icon-split btn-sm" data-toggle="modal" data-target="#modal2">
                    <span class="text">Finalizar visita</span>
                    
                    <span class="icon text-white-50">
                        <i class="fas fa-door-open"></i>
                    </span>
                </a>
            {% endif %}
        </div>
    </div>
    
    <div class="card shadow mb-4">        
        <div class="card-body">
            <h4 class="mb-3 text-primary">
                Informações gerais
            </h4>

            {% if form.errors %}
                {% for field in form %}
                    {% if field.errors %}
                        {% for error in field.errors %}
                            <div class="alert alert-dismissible alert-warning" role="alert">
                                {{ error | escape }}
                                <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                                    <span aria-hidden="true">&times;</span>
                                </button>
                            </div>
                        {% endfor %}
                    {% endif %}
                {% endfor %}
            {% endif %}
            
            <form>
                <div class="form-row">
                    <div class="form-group col-md-4">
                        <label>Status</label>
                        <input type="text" class="form-control" value="{{ visitante.get_status_display }}" disabled>
                    </div>

                    <div class="form-group col-md-4">
                        <label>Horário de chegada</label>
                        <input type="text" class="form-control" value="{{ visitante.horario_chegada }}" disabled>
                    </div>

                    <div class="form-group col-md-4">
                        <label>Número da casa a ser visitada</label>
                        <input type="text" class="form-control" value="{{ visitante.numero_casa }}" disabled>
                    </div>
                </div>

                <div class="form-row">
                    <div class="form-group col-md-4">
                        <label>Horário de autorização de entrada</label>
                        <input type="text" class="form-control" value="{{ visitante.get_horario_autorizacao }}" disabled>
                    </div>

                    <div class="form-group col-md-4">
                        <label>Entrada autorizada por</label>
                        <input type="text" class="form-control" value="{{ visitante.get_morador_responsavel }}" disabled>
                    </div>

                    <div class="form-group col-md-4">
                        <label>Horário de saída</label>
                        <input type="text" class="form-control" value="{{ visitante.get_horario_saida }}" disabled>
                    </div>
                </div>
            </form>

            <h4 class="mb-3 mt-4 text-primary">
                Informações pessoais
            </h4>

            <form>
                <div class="form-row">
                    <div class="form-group col-md-6">
                        <label>Nome completo</label>
                        <input type="text" class="form-control" value="{{ visitante.nome_completo }}" disabled>
                    </div>

                    <div class="form-group col-md-6">
                        <label>CPF</label>
                        <input type="text" class="form-control" value="{{ visitante.get_cpf }}" disabled>
                    </div>
                </div>

                <div class="form-row">
                    <div class="form-group col-md-6">
                        <label>Data de nascimento</label>
                        <input type="text" class="form-control" value="{{ visitante.data_nascimento }}" disabled>
                    </div>

                    <div class="form-group col-md-6">
                        <label>Placa do veículo</label>
                        <input type="text" class="form-control" value="{{ visitante.get_placa_veiculo }}" disabled>
                    </div>
                </div>
            </form>
            
            <p class="mr-2 mt-3 mb-4 text-right">
                <small>
                    Visitante registrado em {{ visitante.horario_chegada }} por {{ visitante.registrado_por }}
                </small>
            </p>

            <div class="mr-1 text-right">
                <a href="{{ request.META.HTTP_REFERER }}" class="btn btn-secondary text-white" type="button">
                    <span class="text">Voltar</span>
                </a>
            </div>
        </div>
    </div>

    <div class="modal fade" id="modal1" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
        <div class="modal-dialog" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title" id="exampleModalLabel">Autorizar entrada de visitante</h5>
                    
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
            
                <div class="modal-body">
                    <form method="post">
                        {% csrf_token %}

                        <div class="form-group">
                            <label for="id_morador_responsavel" class="col-form-label">Nome do morador responsável por autorizar a entrada do visitante:</label>
                            {{ form.morador_responsavel | add_class:"form-control"  }}
                        </div>

                        <div class="modal-footer">
                            <button type="button" class="btn btn-secondary" data-dismiss="modal">Cancelar</button>
                            <button type="submit" class="btn btn-primary">Autorizar entrada</button>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>

    <div class="modal fade" id="modal2" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
        <div class="modal-dialog" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title" id="exampleModalLabel">Finalizar visita</h5>
                    
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
            
                <div class="modal-body">
                    <div class="modal-body">
                        <h5 class="mb-3">
                            Realmente deseja encerrar a visita?
                        </h5>

                        <form method="post" action="{% url 'finalizar_visita' id=visitante.id %}">
                            {% csrf_token %}

                            <input hidden>

                            <div class="modal-footer">
                                <button type="button" class="btn btn-secondary" data-dismiss="modal">Cancelar</button>
                                <button type="submit" class="btn btn-primary">Finalizar visita</button>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

apps/visitantes/templates/registrar_visitante.html
{% extends 'base.html' %}
 
{% load widget_tweaks %}
 
{% block conteudo %}

{% block title %}Informações{% endblock %}

<div class="container">
                        <div class="d-sm-flex align-items-center justify-content-between mb-4">
                            <h1 class="h3 mb-0 text-gray-800">{{ nome_pagina }}</h1>
                        </div>
 
                        <div class="card shadow mb-4">
                            <div class="card-body">
                                <h4 class="mb-3 text-primary">
                                    Formulário para registro de novo Visitante
                                </h4>

                                <p class="mb-5 ml-1">
                                    <small>
                                        O asterístico (*) indica que o campo é OBRIGATÓRIO.
                                    </small>
                                </p>

                                {% if form.errors %}
                                    {% for field in form %}
                                        {% if field.errors %}
                                            {% for erro in field.errors %}
                                                <div class="alert alert-warning" role="alert">
                                                    {{ erro }}
                                                </div>
                                            {% endfor %}
                                        {% endif %}
                                    {% endfor %}
                                {% endif %}
 
                                <form method="post">
                                    <div class="form-row">
                                        {% csrf_token %}
 
                                        {% for field in form %}
                                            <div class="form-group col-md-12">
                                                <label>{{ field.label }} {% if field.field.required %} * {% endif %}</label>
                                                {% render_field field placeholder=field.label class="form-control" %}
                                            </div>
                                        {% endfor %}
 
                                    </div>
                                    <div class='text-rigth'> 
                                        <a href="{% url 'index' %}" class="btn btn-secondary text-white" type="button">
                                        <span class="text">Cancelar</span>
                                    </a>
                                    
                                        <button class="btn btn-primary" type="submit">
                                            <span class="text">Registrar Visitante</span>

                                        </button>
                                    </div>
                                </form>
 
                            </div>
                        </div>
                    </div>
{% endblock conteudo %}